In [1]:
import os
os.chdir('..')

In [2]:
%pwd

'e:\\MLOPS\\bid_bot_detection'

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Import

In [4]:
bids = pd.read_csv('data/raw/bids.csv', sep=',')
print('bids: OK {}'.format(bids.shape))
bids.head()
# bids = pd.read_csv('data/bids_normalized.csv', sep=',')
# print('bids: OK {}'.format(bids.shape))
# bids.head()

bids: OK (7656334, 9)

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
0,0,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,jewelry,phone0,9759243157894736,us,69.166.231.58,vasstdc27m7nks3
1,1,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone1,9759243157894736,in,50.201.125.84,jmqlhflrzwuay9c
2,2,aa5f360084278b35d746fa6af3a7a1a5ra3xe,wa00e,home goods,phone2,9759243157894736,py,112.54.208.157,vasstdc27m7nks3
3,3,3939ac3ef7d472a59a9c5f893dd3e39fh9ofi,jefix,jewelry,phone4,9759243157894736,in,18.99.175.133,vasstdc27m7nks3
4,4,8393c48eaf4b8fa96886edc7cf27b372dsibi,jefix,jewelry,phone5,9759243157894736,in,145.138.5.37,vasstdc27m7nks3

In [5]:
b_train = pd.read_csv('data/raw/train.csv', sep=',')
print('b_train: OK: {}'.format(b_train.shape))
b_train.head()
# b_train = pd.read_csv('data/b_train.csv', sep=',')
# print('b_train: OK: {}'.format(b_train.shape))
# b_train.head()

b_train: OK: (2013, 4)

,bidder_id,payment_account,address,outcome
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0
1,624f258b49e77713fc34034560f93fb3hu3jo,a3d2de7675556553a5f08e4c88d2c228v1sga,ae87054e5a97a8f840a3991d12611fdcrfbq3,0.0
2,1c5f4fc669099bfbfac515cd26997bd12ruaj,a3d2de7675556553a5f08e4c88d2c2280cybl,92520288b50f03907041887884ba49c0cl0pd,0.0
3,4bee9aba2abda51bf43d639013d6efe12iycd,51d80e233f7b6a7dfdee484a3c120f3b2ita8,4cb9717c8ad7e88a9a284989dd79b98dbevyi,0.0
4,4ab12bc61c82ddd9c2d65e60555808acqgos1,a3d2de7675556553a5f08e4c88d2c22857ddh,2a96c3ce94b3be921e0296097b88b56a7x1ji,0.0

# Preprocessing

## bids_normalized table

In [6]:
bids.head()

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
0,0,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,jewelry,phone0,9759243157894736,us,69.166.231.58,vasstdc27m7nks3
1,1,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone1,9759243157894736,in,50.201.125.84,jmqlhflrzwuay9c
2,2,aa5f360084278b35d746fa6af3a7a1a5ra3xe,wa00e,home goods,phone2,9759243157894736,py,112.54.208.157,vasstdc27m7nks3
3,3,3939ac3ef7d472a59a9c5f893dd3e39fh9ofi,jefix,jewelry,phone4,9759243157894736,in,18.99.175.133,vasstdc27m7nks3
4,4,8393c48eaf4b8fa96886edc7cf27b372dsibi,jefix,jewelry,phone5,9759243157894736,in,145.138.5.37,vasstdc27m7nks3

### 1. time normalized

In [7]:
min_time = bids['time'].min()
bids['time_normalized'] = round((bids['time'] - min_time) * 19 / 1e9,2)
pd.DataFrame(bids.time_normalized.unique())
bids.head()

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url,time_normalized
0,0,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,jewelry,phone0,9759243157894736,us,69.166.231.58,vasstdc27m7nks3,2419200.0
1,1,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone1,9759243157894736,in,50.201.125.84,jmqlhflrzwuay9c,2419200.0
2,2,aa5f360084278b35d746fa6af3a7a1a5ra3xe,wa00e,home goods,phone2,9759243157894736,py,112.54.208.157,vasstdc27m7nks3,2419200.0
3,3,3939ac3ef7d472a59a9c5f893dd3e39fh9ofi,jefix,jewelry,phone4,9759243157894736,in,18.99.175.133,vasstdc27m7nks3,2419200.0
4,4,8393c48eaf4b8fa96886edc7cf27b372dsibi,jefix,jewelry,phone5,9759243157894736,in,145.138.5.37,vasstdc27m7nks3,2419200.0

In [8]:
min_time = bids['time'].min()
bids['time_normalized'] = round((bids['time'] - min_time) * 19/1e9, 2)

In [9]:
pd.DataFrame(bids.time_normalized.unique()) # shows that we succesfully increment the time 1 at a time
bids.head()

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url,time_normalized
0,0,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,jewelry,phone0,9759243157894736,us,69.166.231.58,vasstdc27m7nks3,2419200.0
1,1,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone1,9759243157894736,in,50.201.125.84,jmqlhflrzwuay9c,2419200.0
2,2,aa5f360084278b35d746fa6af3a7a1a5ra3xe,wa00e,home goods,phone2,9759243157894736,py,112.54.208.157,vasstdc27m7nks3,2419200.0
3,3,3939ac3ef7d472a59a9c5f893dd3e39fh9ofi,jefix,jewelry,phone4,9759243157894736,in,18.99.175.133,vasstdc27m7nks3,2419200.0
4,4,8393c48eaf4b8fa96886edc7cf27b372dsibi,jefix,jewelry,phone5,9759243157894736,in,145.138.5.37,vasstdc27m7nks3,2419200.0

### 2. outcome

In [10]:
bids['outcome'] = bids.merge(b_train, how='left', on='bidder_id').outcome

### other

In [11]:
del bids['merchandise']
del bids['device']
del bids['country']
del bids['ip']
del bids['url']
bids.to_csv('data/processed/bids_normalized_short.csv', sep=',', header=True, index=False)

In [12]:
bids

,bid_id,bidder_id,auction,time,time_normalized,outcome
0,0,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,9759243157894736,2419200.0,NaN
1,1,668d393e858e8126275433046bbd35c6tywop,aeqok,9759243157894736,2419200.0,0.0
2,2,aa5f360084278b35d746fa6af3a7a1a5ra3xe,wa00e,9759243157894736,2419200.0,NaN
3,3,3939ac3ef7d472a59a9c5f893dd3e39fh9ofi,jefix,9759243157894736,2419200.0,NaN
4,4,8393c48eaf4b8fa96886edc7cf27b372dsibi,jefix,9759243157894736,2419200.0,NaN
...,...,...,...,...,...,...
7656329,7656329,626159dd6f2228ede002d9f9340f75b7puk8d,3e64w,9709222052631578,1468799.0,NaN
7656330,7656330,a318ea333ceee1ba39a494476386136a826dv,xn0y0,9709222052631578,1468799.0,NaN
7656331,7656331,f5b2bbad20d1d7ded3ed960393bec0f40u6hn,gja6c,9709222052631578,1468799.0,0.0
7656332,7656332,d4bd412590f5106b9d887a43c51b254eldo4f,hmwk8,9709222052631578,1468799.0,NaN
7656333,7656333,0ea62aaa9c3ffcc6db584cb69c1f6c4bcripp,c9ox9,9709222052631578,1468799.0,NaN

## features for b_train & b_test table

In [13]:
del b_train['address']
del b_train['payment_account']

In [14]:
b_train

                                  bidder_id  outcome
0     91a3c57b13234af24875c56fb7e2b2f4rb56a      0.0
1     624f258b49e77713fc34034560f93fb3hu3jo      0.0
2     1c5f4fc669099bfbfac515cd26997bd12ruaj      0.0
3     4bee9aba2abda51bf43d639013d6efe12iycd      0.0
4     4ab12bc61c82ddd9c2d65e60555808acqgos1      0.0
...                                     ...      ...
2008  369515b3af4f8ca582f90271d30b14b6r52aw      0.0
2009  f939c17ffc7c39ac9b35b69e5e75179fv9pe2      0.0
2010  c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl      0.0
2011  0381a69b7a061e9ace2798fd48f1f537mgq57      0.0
2012  84a769adc98498f52debfe57b93a0789556f4      0.0

[2013 rows x 2 columns]

### 1. mean_time_diff

In [21]:
mean_time_diff = (
    bids.sort_values(['bidder_id', 'time_normalized'])
        .groupby('bidder_id')['time_normalized']
        .diff()
        .groupby(bids['bidder_id'])
        .mean()
        .round(4)
        .reset_index(name='mean_time_diff')
)
b_train = b_train.drop(columns=['mean_time_diff'], errors='ignore')
b_train = b_train.merge(mean_time_diff, on='bidder_id', how='left')

### 2. total_bids

In [23]:
total_bids = (
    bids
        .groupby('bidder_id')
        .size()
        .reset_index(name='total_bids')
)

b_train = b_train.merge(total_bids, on='bidder_id', how='left')

b_train['total_bids'] = b_train['total_bids'].fillna(0).astype(int)

In [25]:
b_train

,bidder_id,outcome,mean_time_diff_x,mean_time_diff_y,total_bids_x,mean_time_diff,total_bids_y,total_bids
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,0.0,10851.130435,10851.1304,24,10851.1304,24.0,24
1,624f258b49e77713fc34034560f93fb3hu3jo,0.0,61438.000000,61438.0000,3,61438.0000,3.0,3
2,1c5f4fc669099bfbfac515cd26997bd12ruaj,0.0,45201.000000,45201.0000,4,45201.0000,4.0,4
3,4bee9aba2abda51bf43d639013d6efe12iycd,0.0,NaN,NaN,1,NaN,1.0,1
4,4ab12bc61c82ddd9c2d65e60555808acqgos1,0.0,1477.798701,1477.7987,155,1477.7987,155.0,155
...,...,...,...,...,...,...,...,...
2008,369515b3af4f8ca582f90271d30b14b6r52aw,0.0,0.000000,39884.0857,36,39884.0857,36.0,36
2009,f939c17ffc7c39ac9b35b69e5e75179fv9pe2,0.0,0.000000,NaN,1,NaN,1.0,1
2010,c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl,0.0,0.000000,186171.0000,2,186171.0000,2.0,2
2011,0381a69b7a061e9ace2798fd48f1f537mgq57,0.0,0.000000,NaN,1,NaN,1.0,1
2012,84a769adc98498f52debfe57b93a0789556f4,0.0,0.000000,34.0000,2,34.0000,2.0,2

In [26]:
b_train = b_train[[
    'bidder_id',
    'outcome',
    'mean_time_diff',
    'total_bids'
]]

In [27]:
b_train

,bidder_id,outcome,mean_time_diff,total_bids
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,0.0,10851.1304,24
1,624f258b49e77713fc34034560f93fb3hu3jo,0.0,61438.0000,3
2,1c5f4fc669099bfbfac515cd26997bd12ruaj,0.0,45201.0000,4
3,4bee9aba2abda51bf43d639013d6efe12iycd,0.0,NaN,1
4,4ab12bc61c82ddd9c2d65e60555808acqgos1,0.0,1477.7987,155
...,...,...,...,...
2008,369515b3af4f8ca582f90271d30b14b6r52aw,0.0,39884.0857,36
2009,f939c17ffc7c39ac9b35b69e5e75179fv9pe2,0.0,NaN,1
2010,c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl,0.0,186171.0000,2
2011,0381a69b7a061e9ace2798fd48f1f537mgq57,0.0,NaN,1
2012,84a769adc98498f52debfe57b93a0789556f4,0.0,34.0000,2

### 3. total_auctions

In [28]:
b_train['total_auctions'] = (
    b_train['bidder_id']
        .map(
            bids.groupby('bidder_id')['auction'].nunique()
        )
        .fillna(0)
        .astype(int)
)

C:\Users\User\AppData\Local\Temp\ipykernel_75616\3330678886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  b_train['total_auctions'] = (

In [29]:
b_train

,bidder_id,outcome,mean_time_diff,total_bids,total_auctions
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,0.0,10851.1304,24,18
1,624f258b49e77713fc34034560f93fb3hu3jo,0.0,61438.0000,3,1
2,1c5f4fc669099bfbfac515cd26997bd12ruaj,0.0,45201.0000,4,4
3,4bee9aba2abda51bf43d639013d6efe12iycd,0.0,NaN,1,1
4,4ab12bc61c82ddd9c2d65e60555808acqgos1,0.0,1477.7987,155,23
...,...,...,...,...,...
2008,369515b3af4f8ca582f90271d30b14b6r52aw,0.0,39884.0857,36,25
2009,f939c17ffc7c39ac9b35b69e5e75179fv9pe2,0.0,NaN,1,1
2010,c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl,0.0,186171.0000,2,1
2011,0381a69b7a061e9ace2798fd48f1f537mgq57,0.0,NaN,1,1
2012,84a769adc98498f52debfe57b93a0789556f4,0.0,34.0000,2,1

### 4. bids_per_auction

In [30]:
b_train['bids_per_auction'] = b_train.total_bids.divide(b_train.total_auctions)
b_train['bids_per_auction'] = round(b_train['bids_per_auction'], 4)

C:\Users\User\AppData\Local\Temp\ipykernel_75616\1332195365.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  b_train['bids_per_auction'] = b_train.total_bids.divide(b_train.total_auctions)
C:\Users\User\AppData\Local\Temp\ipykernel_75616\1332195365.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  b_train['bids_per_auction'] = round(b_train['bids_per_auction'], 4)

In [31]:
b_train

,bidder_id,outcome,mean_time_diff,total_bids,total_auctions,bids_per_auction
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,0.0,10851.1304,24,18,1.3333
1,624f258b49e77713fc34034560f93fb3hu3jo,0.0,61438.0000,3,1,3.0000
2,1c5f4fc669099bfbfac515cd26997bd12ruaj,0.0,45201.0000,4,4,1.0000
3,4bee9aba2abda51bf43d639013d6efe12iycd,0.0,NaN,1,1,1.0000
4,4ab12bc61c82ddd9c2d65e60555808acqgos1,0.0,1477.7987,155,23,6.7391
...,...,...,...,...,...,...
2008,369515b3af4f8ca582f90271d30b14b6r52aw,0.0,39884.0857,36,25,1.4400
2009,f939c17ffc7c39ac9b35b69e5e75179fv9pe2,0.0,NaN,1,1,1.0000
2010,c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl,0.0,186171.0000,2,1,2.0000
2011,0381a69b7a061e9ace2798fd48f1f537mgq57,0.0,NaN,1,1,1.0000
2012,84a769adc98498f52debfe57b93a0789556f4,0.0,34.0000,2,1,2.0000

### 5-6. mean_response & min_response

In [32]:
bids_sorted = bids.sort_values(['auction', 'time_normalized'])

bids_sorted['diff'] = (
    bids_sorted
        .groupby('auction')['time_normalized']
        .diff()
)

In [33]:
bids_sorted.to_csv('data/raw/bids_sorted.csv', sep=',', header=True, index=False)

In [34]:
bids_sorted = pd.read_csv('data/raw/bids_sorted.csv', sep=',')
print('bids_sorted: OK {}'.format(bids_sorted.shape))
bids_sorted.head()

bids_sorted: OK (7656334, 7)

,bid_id,bidder_id,auction,time,time_normalized,outcome,diff
0,5826422,92af1e40713e077ef87f5352fb56772fjnzm7,00270,9699049894736842,1275528.0,NaN,NaN
1,5834284,a939f51234ad2c44eb9ccc84e754f41foiv7g,00270,9699098210526315,1276446.0,NaN,918.0
2,5850448,92af1e40713e077ef87f5352fb56772fjnzm7,00270,9699195789473684,1278300.0,NaN,1854.0
3,5884054,9655ccc7c0c193f1549475f02c54dce45kjw7,00270,9699392473684210,1282037.0,1.0,3737.0
4,5898318,9655ccc7c0c193f1549475f02c54dce45kjw7,00270,9699474473684210,1283595.0,1.0,1558.0

In [35]:
bidder_response = (
    bids_sorted
        .groupby('bidder_id')['diff']
        .agg(
            mean_response='mean',
            min_response='min'
        )
        .round(4)
        .reset_index()
)

b_train = b_train.merge(bidder_response, on='bidder_id', how='left')

In [36]:
b_train

,bidder_id,outcome,mean_time_diff,total_bids,total_auctions,bids_per_auction,mean_response,min_response
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,0.0,10851.1304,24,18,1.3333,10673.3750,0.0
1,624f258b49e77713fc34034560f93fb3hu3jo,0.0,61438.0000,3,1,3.0000,2.3333,0.0
2,1c5f4fc669099bfbfac515cd26997bd12ruaj,0.0,45201.0000,4,4,1.0000,219.0000,79.0
3,4bee9aba2abda51bf43d639013d6efe12iycd,0.0,NaN,1,1,1.0000,330.0000,330.0
4,4ab12bc61c82ddd9c2d65e60555808acqgos1,0.0,1477.7987,155,23,6.7391,35.2258,0.0
...,...,...,...,...,...,...,...,...
2008,369515b3af4f8ca582f90271d30b14b6r52aw,0.0,39884.0857,36,25,1.4400,2289.6571,4.0
2009,f939c17ffc7c39ac9b35b69e5e75179fv9pe2,0.0,NaN,1,1,1.0000,4.0000,4.0
2010,c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl,0.0,186171.0000,2,1,2.0000,0.5000,0.0
2011,0381a69b7a061e9ace2798fd48f1f537mgq57,0.0,NaN,1,1,1.0000,0.0000,0.0
2012,84a769adc98498f52debfe57b93a0789556f4,0.0,34.0000,2,1,2.0000,1918.0000,34.0

### 7-8. ip_entropy, url_entropy

In [37]:
def log_entropy(x):
    e = np.sum(np.log(np.array(range(1,np.sum(x)))))
    for i in x:
        e -= np.sum(np.log(np.array(range(1,i))))
    return e

In [39]:
def shannon_entropy(counts):
    p = counts / counts.sum()
    return -(p * np.log(p)).sum()

In [38]:
original_bids = pd.read_csv("data/raw/bids.csv")

original_bids

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
0,0,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,jewelry,phone0,9759243157894736,us,69.166.231.58,vasstdc27m7nks3
1,1,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone1,9759243157894736,in,50.201.125.84,jmqlhflrzwuay9c
2,2,aa5f360084278b35d746fa6af3a7a1a5ra3xe,wa00e,home goods,phone2,9759243157894736,py,112.54.208.157,vasstdc27m7nks3
3,3,3939ac3ef7d472a59a9c5f893dd3e39fh9ofi,jefix,jewelry,phone4,9759243157894736,in,18.99.175.133,vasstdc27m7nks3
4,4,8393c48eaf4b8fa96886edc7cf27b372dsibi,jefix,jewelry,phone5,9759243157894736,in,145.138.5.37,vasstdc27m7nks3
...,...,...,...,...,...,...,...,...,...
7656329,7656329,626159dd6f2228ede002d9f9340f75b7puk8d,3e64w,jewelry,phone91,9709222052631578,ru,140.204.227.63,cghhmomsaxi6pug
7656330,7656330,a318ea333ceee1ba39a494476386136a826dv,xn0y0,mobile,phone236,9709222052631578,pl,24.232.159.118,wgggpdg2gx5pesn
7656331,7656331,f5b2bbad20d1d7ded3ed960393bec0f40u6hn,gja6c,sporting goods,phone80,9709222052631578,za,80.237.28.246,5xgysg14grlersa
7656332,7656332,d4bd412590f5106b9d887a43c51b254eldo4f,hmwk8,jewelry,phone349,9709222052631578,my,91.162.27.152,bhtrek44bzi2wfl
7656333,7656333,0ea62aaa9c3ffcc6db584cb69c1f6c4bcripp,c9ox9,mobile,phone82,9709222052631578,jo,160.243.101.60,vasstdc27m7nks3

In [40]:
ip_entropy = (
    original_bids
        .groupby(['bidder_id', 'ip'])
        .size()
        .groupby('bidder_id')
        .apply(shannon_entropy)
        .round(4)
        .reset_index(name='ip_entropy')
)

In [41]:
url_entropy = (
    original_bids
        .groupby(['bidder_id', 'url'])
        .size()
        .groupby('bidder_id')
        .apply(shannon_entropy)
        .round(4)
        .reset_index(name='url_entropy')
)

In [42]:
b_train = (
    b_train
        .merge(ip_entropy, on='bidder_id', how='left')
        .merge(url_entropy, on='bidder_id', how='left')
)

b_train[['ip_entropy','url_entropy']] = \
    b_train[['ip_entropy','url_entropy']].fillna(0)

### look through

In [43]:
features = ['bidder_id', 'outcome',
         'total_bids', 'total_auctions', 'bids_per_auction',
         'mean_time_diff', 'mean_response', 'min_response',
         'ip_entropy', 'url_entropy']

In [47]:
b_train.tail()

,bidder_id,outcome,mean_time_diff,total_bids,total_auctions,bids_per_auction,mean_response,min_response,ip_entropy,url_entropy
2008,369515b3af4f8ca582f90271d30b14b6r52aw,0.0,39884.0857,36,25,1.44,2289.6571,4.0,0.8130,0.2868
2009,f939c17ffc7c39ac9b35b69e5e75179fv9pe2,0.0,NaN,1,1,1.00,4.0000,4.0,-0.0000,-0.0000
2010,c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl,0.0,186171.0000,2,1,2.00,0.5000,0.0,0.6931,-0.0000
2011,0381a69b7a061e9ace2798fd48f1f537mgq57,0.0,NaN,1,1,1.00,0.0000,0.0,-0.0000,-0.0000
2012,84a769adc98498f52debfe57b93a0789556f4,0.0,34.0000,2,1,2.00,1918.0000,34.0,-0.0000,-0.0000

In [48]:
b_train.fillna(0, inplace=True)

### save

In [49]:
b_train.to_csv('data/processed/b_train.csv', sep=',', header=True, index=False)